# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_likelihood <- function(dat, mu, sd) {
    .Call(`_mcmcTuto_log_likelihood`, dat, mu, sd)
}

log_prior_mu <- function(mu, prior_mu, prior_sd) {
    .Call(`_mcmcTuto_log_prior_mu`, mu, prior_mu, prior_sd)
}

log_prior_sd <- function(sd) {
    .Call(`_mcmcTuto_log_prior_sd`, sd)
}

log_prior_total <- function(mu, sd, prior_mu, prior_sd) {
    .Call(`_mcmcTuto_log_prior_total`, mu, sd, prior_mu, prior_sd)
}

log_posterior <- function(dat, mu, sd, prior_mu, prior_sd) {
    .Call(`_mcmcTuto_log_posterior`, dat, mu, sd, prior_mu, prior_sd)
}

mcmc <- function(n_iter, init_mu, init_sd, sd_proposal_mu, sd_proposal_sd, dat, prior_mu, prior_sd) {
    .Call(`_mcmcTuto_mcmc`, n_iter, init_mu, init_sd, sd_proposal_mu, sd_proposal_sd, dat, prior_mu, prior_sd)
}

move_mu <- function(curr_mu, curr_sd, sd_proposal_mu, dat, prior_mu, prior_sd) {
    .Call(`_mcmcTuto_move_mu`, curr_mu, curr_sd, sd_proposal_mu, dat, prior_mu, prior_sd)
}

move_sd <- function(curr_mu, curr_sd, sd_proposal_sd, dat, prior_mu, prior_sd) {
    .Call(`_mcmcTuto_move_sd`, curr_mu, curr_sd, sd_proposal_sd, dat, prior_mu, prior_sd)
}

